// import { Client } from "pg";
// import {
//   AuthPublicState,
//   AuthConnection,
//   AuthControls,
// } from "../../../controllers/sql/schemas/__auths__.tables";
// import { sqlDBs } from "../../../app";

// export function authenticateUser(
//   uid: string, // user's id (username, email or token)
//   verifications: string[][], // [tokens, emails, phones, pubkeys, oauths, netowork & devices ips]
//   ukey?: string, // user's autogenerated password (555 bits)
//   recovryToken?: string, // unique user's recovery token (1024 bits)
//   _db = sqlDBs.auths // db client
// ): boolean {
//   const authState = {} as AuthState;
//   const authControls: AuthControls = {
//     authenticated: false,
//     verified: false,
//     userInput: "",
//     newUser: true,
//   };
//   const nowTime = BigInt(Date.now());

//   authState.controls = { ...authControls };
//   return authState;
// }
