// TODO: Logs ____portal____ queries
// TODO: Logs ____marketplace____ queries
// TODO: Logs ____games____ queries
// TODO: Logs ____dao____ queries
// TODO: Sockets ____current_____ queries
// TODO: Sockets ____history_____ queries
// TODO: Sockets ____logs_____ queries
// TODO: Sockets ____errors_____ queries
// TODO: Blacklist ____ipblacklist____ queries
// TODO: Blacklist ____bannedaccounts____ queries
