/* @/global/constants/langs.constants.ts */

/*** LANGUAGES CONSTANTS ***/

export const flags = {
  af: "🇦🇫",
  al: "🇦🇱",
  dz: "🇩🇿",
  us: "🇺🇸",
  sa: "🇸🇦",
  eg: "🇪🇬",
  ar: "🇦🇷",
  au: "🇦🇺",
  at: "🇦🇹",
  az: "🇦🇿",
  bh: "🇧🇭",
  bd: "🇧🇩",
  be: "🇧🇪",
  bo: "🇧🇴",
  ba: "🇧🇦",
  br: "🇧🇷",
  gb: "🇬🇧",
  bg: "🇧🇬",
  mm: "🇲🇲",
  kh: "🇰🇭",
  ca: "🇨🇦",
  cl: "🇨🇱",
  cn: "🇨🇳",
  co: "🇨🇴",
  cr: "🇨🇷",
  hr: "🇭🇷",
  cu: "🇨🇺",
  cz: "🇨🇿",
  dk: "🇩🇰",
  do: "🇩🇴",
  nl: "🇳🇱",
  ec: "🇪🇨",
  ae: "🇦🇪",
  ee: "🇪🇪",
  et: "🇪🇹",
  ph: "🇵🇭",
  fi: "🇫🇮",
  fr: "🇫🇷",
  gq: "🇬🇶",
  ge: "🇬🇪",
  de: "🇩🇪",
  gr: "🇬🇷",
  gt: "🇬🇹",
  hn: "🇭🇳",
  HK: "🇭🇰",
  hu: "🇭🇺",
  is: "🇮🇸",
  in: "🇮🇳",
  id: "🇮🇩",
  ir: "🇮🇷",
  iq: "🇮🇶",
  ie: "🇮🇪",
  il: "🇮🇱",
  it: "🇮🇹",
  jp: "🇯🇵",
  jo: "🇯🇴",
  kz: "🇰🇿",
  ke: "🇰🇪",
  kw: "🇰🇼",
  la: "🇱🇦",
  lv: "🇱🇻",
  lb: "🇱🇧",
  ly: "🇱🇾",
  lt: "🇱🇹",
  mk: "🇲🇰",
  my: "🇲🇾",
  mt: "🇲🇹",
  mx: "🇲🇽",
  xa: "🌍",
  mn: "🇲🇳",
  ma: "🇲🇦",
  np: "🇳🇵",
  nz: "🇳🇿",
  ni: "🇳🇮",
  ng: "🇳🇪",
  no: "🇳🇴",
  om: "🇴🇲",
  pk: "🇵🇰",
  pa: "🇵🇦",
  py: "🇵🇾",
  pe: "🇵🇪",
  pl: "🇵🇱",
  pt: "🇵🇹",
  pr: "🇵🇷",
  qa: "🇶🇦",
  ro: "🇷🇴",
  ru: "🇷🇺",
  sv: "🇸🇻",
  rs: "🇷🇸",
  sg: "🇸🇬",
  sk: "🇸🇰",
  si: "🇸🇮",
  so: "🇸🇴",
  za: "🇿🇦",
  kr: "🇰🇷",
  es: "🇪🇸",
  lk: "🇱🇰",
  se: "🇸🇪",
  ch: "🇨🇭",
  sy: "🇸🇾",
  CN: "🇹🇼",
  tz: "🇹🇿",
  th: "🇹🇭",
  tn: "🇹🇳",
  tr: "🇹🇷",
  ua: "🇺🇦",
  uy: "🇺🇾",
  uz: "🇺🇿",
  ve: "🇻🇪",
  vn: "🇻🇳",
  wls: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  ye: "🇾🇪",
};

export const languages = {
  "Afghan Pashto": ["af"],
  Albanian: ["al"],
  "Algerian Arabic": ["dz"],
  "American English": ["us"],
  "American Spanish": ["us"],
  Arabic: ["sa", "eg", "bh", "ae", "ly", "iq", "om", "sa", "sy", "tn", "ye"],
  "Argentinean Spanish": ["ar"],
  "Australian English": ["au"],
  "Austrian German": ["at"],
  Azerbaijani: ["az"],
  "Bangladeshi Bengali": ["bd"],
  "Belgian Dutch": ["be"],
  "Belgian French": ["be"],
  "Bolivian Spanish": ["bo"],
  "Bosnian - Herzegovinian Bosnian": ["ba"],
  "Brazilian Portuguese": ["br"],
  "British English": ["gb"],
  "British Welsh": ["gb", "wls"],
  Bulgarian: ["bg"],
  Burmese: ["mm"],
  "Cambodian Khmer": ["kh"],
  "Canadian English": ["ca"],
  "Canadian French": ["ca"],
  "Chilean Spanish": ["cl"],
  Chinese: ["cn", "cn", "HK", "HK", "TW"],
  "Colombian Spanish": ["co"],
  Croatian: ["hr"],
  "Cuban Spanish": ["cu"],
  Czech: ["cz"],
  Danish: ["dk"],
  "Dominican (Dominican Republic) Spanish": ["do"],
  Dutch: ["nl", "be"],
  "Ecuadorean Spanish": ["ec"],
  "Egyptian Arabic": ["eg"],
  "Emirian Arabic": ["ae"],
  English: ["us", "gb", "au", "ca", "za", "ng", "tz"],
  "Equatorial Guinean Spanish": ["gq"],
  Estonian: ["ee"],
  "Ethiopian Amharic": ["et"],
  Filipino: ["ph", "ph"],
  Finnish: ["fi"],
  French: ["fr", "be", "ca", "ch"],
  Georgian: ["ge"],
  German: ["de", "at", "ch"],
  Greek: ["gr"],
  "Guatemalan Spanish": ["gt"],
  "Honduran Spanish": ["hn"],
  "Hong Kong Chinese": ["CN", "HK"],
  "Hong Kong English": ["CN", "HK"],
  Hungarian: ["hu"],
  Icelandic: ["is"],
  "Indian Bengali": ["in"],
  "Indian English": ["in"],
  "Indian Gujarati": ["in"],
  "Indian Hindi": ["in"],
  "Indian Kannada": ["in"],
  "Indian Malayalam": ["in"],
  "Indian Marathi": ["in"],
  "Indian Panjabi": ["in"],
  "Indian Tamil": ["in"],
  "Indian Telugu": ["in"],
  "Indian Urdu": ["in", "pk"],
  Indonesian: ["id"],
  "Indonesian Javanese": ["id"],
  "Indonesian Sundanese": ["id"],
  "Iranian Persian": ["ir"],
  Irish: ["ie", "ie"],
  "Israeli Hebrew": ["il"],
  Italian: ["it"],
  Japanese: ["jp"],
  "Jordanian Arabic": ["jo"],
  "Kazakhstani Kazakh": ["kz"],
  "Kenyan English": ["ke"],
  "Kenyan Swahili": ["ke", "tz"],
  "Kuwaiti Arabic": ["kw"],
  "Laotian Lao": ["la"],
  Latvian: ["lv"],
  "Lebanese Arabic": ["lb"],
  "Libyan Arabic": ["ly"],
  Lithuanian: ["lt"],
  Macedonian: ["mk"],
  "Malaysian Malay": ["my"],
  "Malaysian Tamil": ["my"],
  Maltese: ["mt"],
  "Mexican Spanish": ["mx"],
  "Modern Standard Arabic": ["xa"],
  Mongolian: ["mn"],
  "Moroccan Arabic": ["ma"],
  "Nepalese Nepali": ["np"],
  "New Zealander English": ["nz"],
  "Nicaraguan Spanish": ["ni"],
  "Nigerien English": ["ng"],
  "Norwegian Bokmål": ["no"],
  "Omani Arabic": ["om"],
  "Pakistani Urdu": ["pk"],
  "Panamanian Spanish": ["pa"],
  "Paraguayan Spanish": ["py"],
  "Peruvian Spanish": ["pe"],
  Polish: ["pl"],
  Portuguese: ["pt", "br"],
  "Puerto Rico Spanish": ["pr"],
  "Qatari Arabic": ["qa"],
  Romanian: ["ro"],
  Russian: ["ru"],
  "Salvadoran Spanish": ["sv"],
  "Saudi Arabic": ["sa"],
  Serbian: ["rs"],
  "Singaporean English": ["sg"],
  "Singaporean Tamil": ["sg"],
  Slovak: ["sk"],
  Slovenian: ["si"],
  Somali: ["so"],
  "South African Afrikaans": ["za"],
  "South African English": ["za"],
  "South African Zulu": ["za"],
  "South Korean": ["kr"],
  Spanish: ["mx", "es", "ar", "co", "uy", "ve"],
  "Spanish Catalan": ["es"],
  "Spanish Galician": ["es"],
  "Sri Lankan Sinhala": ["lk"],
  "Sri Lankan Tamil": ["lk"],
  Swedish: ["se"],
  "Swiss French": ["ch"],
  "Swiss German": ["ch"],
  "Syrian Arabic": ["sy"],
  "Taiwanese Chinese": ["CN"],
  "Tanzanian English": ["tz"],
  "Tanzanian Swahili": ["tz"],
  Thai: ["th"],
  "Tunisian Arabic": ["tn"],
  Turkish: ["tr"],
  Ukrainian: ["ua"],
  "Uruguayan Spanish": ["uy"],
  Uzbek: ["uz"],
  "Venezuelan Spanish": ["ve"],
  Vietnamese: ["vn"],
  "Welsh English": ["wls"],
  "Yemenite Arabic": ["ye"],
};

export const LANGS_CONSTANTS = {
  flags,
  languages,
};

export default LANGS_CONSTANTS;

/* END OF SCRIPT */
/* v1.0 */
/* Last update: 2023-05-10 */
